### ISSUE TITLE
Failed to load the language-syntax-settings package

### ISSUE THREAD

**Issue by nmccready** [ardcore/atom-language-settings#8]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [language-syntax-settings](https://github.com/ardcore/atom-language-settings) package, v2.6.0
### Stack Trace

Failed to load the language-syntax-settings package

```
At evalmachine.<anonymous>:1
const END = 0, NEWLINE = 1, SEMICOLON = 2, COMMA = 3, ASSIGN = 4, HOOK = 5, CO
^
Identifier 'END' has already been declared

evalmachine.<anonymous>:1
const END = 0, NEWLINE = 1, SEMICOLON = 2, COMMA = 3, ASSIGN = 4, HOOK = 5, CO
^
TypeError: Identifier 'END' has already been declared
  at evalmachine.<anonymous>:1:1
  at Object.exports.runInThisContext (vm.js:76:17)
  at global.eval (/Users/nem/.atom/packages/language-syntax-settings/node_modules/loophole/lib/loophole.js:12:19)
  at /Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/node_modules/js2coffee/out/lib/narcissus_packed.js:894:5
  at Object.<anonymous> (/Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/node_modules/js2coffee/out/lib/narcissus_packed.js:2274:2)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (/Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/node_modules/js2coffee/out/lib/js2coffee.js:11:12)
  at Object.<anonymous> (/Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/node_modules/js2coffee/out/lib/js2coffee.js:1144:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (/Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/out/lib/cson.js:7:15)
  at Object.<anonymous> (/Users/nem/.atom/packages/language-syntax-settings/node_modules/cson/out/lib/cson.js:134:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at /Users/nem/.atom/packages/language-syntax-settings/lib/language-settings.coffee:4:27
  at exports.allowUnsafeEval (/Users/nem/.atom/packages/language-syntax-settings/node_modules/loophole/lib/loophole.js:14:14)
  at Object.<anonymous> (/Users/nem/.atom/packages/language-syntax-settings/lib/language-settings.coffee:4:8)
  at Object.<anonymous> (/Users/nem/.atom/packages/language-syntax-settings/lib/language-settings.coffee:2:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:622:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:51:25)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Stylus, v0.6.0
atom-color-highlight, v3.0.8
atom-text-transformer, v0.4.0
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
coffee-compile, v0.11.0
coffee-lint, v0.7.3
color-picker, v1.4.4
command-logger, v0.22.0
hide-files, v0.1.5
highlight-line, v0.10.1
highlight-selected, v0.9.1
html-helper, v0.2.3
indent-guide-ext, v0.1.0
jslint, v1.2.0
language-coffee-script, v0.38.1
language-jade, v0.3.0
language-javascript-semantic, v0.1.0
language-nginx, v0.4.0
language-scala, v1.1.0
language-stylus, v0.1.0
language-syntax-settings, v2.6.0
linter-erb, v0.1.0
linter-scalac, v0.3.3
pain-split, v1.3.1
project-palette-finder, v2.4.16
recent-files, v0.3.0
refactor, v0.4.1
show-in-folder, v0.1.0
svg-preview, v0.5.1
tabular, v0.1.0
view-tail-large-files, v0.1.13

# Dev
No dev packages
```

**Comment by mikecg** [comment]
I have the same issue.

**Comment by FyerPower** [comment]
same issue here

**Comment by Qualphey** [comment]
same

**Comment by andrewcstewart** [comment]
+1

**Comment by hoppfrosch** [comment]
+1

**Comment by hoppfrosch** [comment]
+1

**Comment by andomain** [comment]
+1

**Comment by allenmoore** [comment]
+1 for this also.

**Comment by Str3tched-by-Design** [comment]
+1

**Comment by ghost** [comment]
+1
